version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &build-packages
    run:
      name: Build
      command: npm run build

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install PNPM
          command: "sudo npm install -g pnpm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: pnpm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: pnpm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
